### ISSUE TITLE
Error when trying to install in Datalogic Skorpio X4

### ISSUE THREAD

**Issue by DavidVinicius** [datalogic/ionic-samples#2]
When I try to install DecodeListener App I get a crash. I simply cloned this repository and build the APK.

Does anyone know how to help me?

**Comment by codybrookshear** [comment]
Hi @DavidVinicius  

Sorry for the delay. It looks like the problem is that our samples (including DecodeListener) use a 2.x version of webview that isn't compatible with 4.4 devices.  This [blog post](https://ionic.zone/debug/ionic-and-android-4) describes the problem in detail.

I was able to get the app to run successfully on a Datalogic 4.4 device (DL-Axist in my case), using these commands:

```bash
cd DecodeListener
ionic cordova plugin rm cordova-plugin-ionic-webview
ionic cordova plugin add cordova-plugin-ionic-webview@1.2.1
ionic cordova platforms remove android
rm -rf plugins
ionic cordova run android --device
```
